# Generated by Django 5.2 on 2025-05-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.ImageField(upload_to='')),
                ('image_random_num', models.IntegerField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
